// ========================================
// Shoal Area Export
// ========================================
// Shoal: Bluefin
// Shoal ID: 59738
// Generated: 2025-12-21 03:06:34
// Total waypoints: 204
// Stop points: 10
// Area-based stop duration: 70 ticks
// ========================================

package com.duckblade.osrs.sailing.features.trawling.ShoalPathData;

import com.duckblade.osrs.sailing.features.trawling.Shoal;
import com.duckblade.osrs.sailing.features.trawling.ShoalAreaData;
import com.duckblade.osrs.sailing.features.trawling.ShoalWaypoint;
import net.runelite.api.coords.WorldArea;
import net.runelite.api.coords.WorldPoint;

/**
 * Shoal area definition for Bluefin (ID: 59738)
 * Contains waypoint path, area bounds, and stop duration.
 * Generated by ShoalPathTracker on 2025-12-21 03:06:34
 */
public class BluefinRainbowReef implements ShoalAreaData {

	public static final WorldArea AREA = new WorldArea(2099, 2211, 287, 190, 0);
	public static final Shoal SHOAL_TYPE = Shoal.BLUEFIN;

	public static final ShoalWaypoint[] WAYPOINTS = {
		new ShoalWaypoint(new WorldPoint(2153, 2337, 0), true),
		new ShoalWaypoint(new WorldPoint(2185, 2367, 0), false),
		new ShoalWaypoint(new WorldPoint(2201, 2374, 0), false),
		new ShoalWaypoint(new WorldPoint(2202, 2385, 0), false),
		new ShoalWaypoint(new WorldPoint(2195, 2391, 0), false),
		new ShoalWaypoint(new WorldPoint(2164, 2391, 0), false),
		new ShoalWaypoint(new WorldPoint(2147, 2384, 0), true),
		new ShoalWaypoint(new WorldPoint(2141, 2376, 0), false),
		new ShoalWaypoint(new WorldPoint(2115, 2361, 0), false),
		new ShoalWaypoint(new WorldPoint(2113, 2358, 0), false),
		new ShoalWaypoint(new WorldPoint(2113, 2336, 0), false),
		new ShoalWaypoint(new WorldPoint(2136, 2321, 0), true),
		new ShoalWaypoint(new WorldPoint(2139, 2317, 0), false),
		new ShoalWaypoint(new WorldPoint(2137, 2286, 0), false),
		new ShoalWaypoint(new WorldPoint(2133, 2282, 0), false),
		new ShoalWaypoint(new WorldPoint(2124, 2281, 0), false),
		new ShoalWaypoint(new WorldPoint(2109, 2262, 0), false),
		new ShoalWaypoint(new WorldPoint(2109, 2248, 0), true),
		new ShoalWaypoint(new WorldPoint(2115, 2235, 0), false),
		new ShoalWaypoint(new WorldPoint(2119, 2233, 0), false),
		new ShoalWaypoint(new WorldPoint(2140, 2236, 0), false),
		new ShoalWaypoint(new WorldPoint(2159, 2262, 0), false),
		new ShoalWaypoint(new WorldPoint(2173, 2262, 0), false),
		new ShoalWaypoint(new WorldPoint(2183, 2256, 0), false),
		new ShoalWaypoint(new WorldPoint(2185, 2246, 0), true),
		new ShoalWaypoint(new WorldPoint(2189, 2226, 0), false),
		new ShoalWaypoint(new WorldPoint(2195, 2221, 0), false),
		new ShoalWaypoint(new WorldPoint(2227, 2221, 0), false),
		new ShoalWaypoint(new WorldPoint(2252, 2224, 0), false),
		new ShoalWaypoint(new WorldPoint(2256, 2230, 0), false),
		new ShoalWaypoint(new WorldPoint(2258, 2251, 0), false),
		new ShoalWaypoint(new WorldPoint(2267, 2257, 0), false),
		new ShoalWaypoint(new WorldPoint(2271, 2257, 0), true),
		new ShoalWaypoint(new WorldPoint(2299, 2256, 0), false),
		new ShoalWaypoint(new WorldPoint(2320, 2235, 0), false),
		new ShoalWaypoint(new WorldPoint(2347, 2235, 0), false),
		new ShoalWaypoint(new WorldPoint(2363, 2243, 0), false),
		new ShoalWaypoint(new WorldPoint(2376, 2259, 0), false),
		new ShoalWaypoint(new WorldPoint(2376, 2267, 0), true),
		new ShoalWaypoint(new WorldPoint(2375, 2278, 0), false),
		new ShoalWaypoint(new WorldPoint(2362, 2294, 0), false),
		new ShoalWaypoint(new WorldPoint(2343, 2303, 0), false),
		new ShoalWaypoint(new WorldPoint(2338, 2303, 0), true),
		new ShoalWaypoint(new WorldPoint(2316, 2304, 0), false),
		new ShoalWaypoint(new WorldPoint(2311, 2305, 0), false),
		new ShoalWaypoint(new WorldPoint(2296, 2293, 0), false),
		new ShoalWaypoint(new WorldPoint(2280, 2288, 0), false),
		new ShoalWaypoint(new WorldPoint(2269, 2277, 0), false),
		new ShoalWaypoint(new WorldPoint(2258, 2272, 0), true),
		new ShoalWaypoint(new WorldPoint(2238, 2272, 0), false),
		new ShoalWaypoint(new WorldPoint(2233, 2275, 0), false),
		new ShoalWaypoint(new WorldPoint(2201, 2275, 0), false),
		new ShoalWaypoint(new WorldPoint(2199, 2275, 0), true),
		new ShoalWaypoint(new WorldPoint(2168, 2275, 0), false),
		new ShoalWaypoint(new WorldPoint(2155, 2279, 0), false),
		new ShoalWaypoint(new WorldPoint(2147, 2292, 0), false),
		new ShoalWaypoint(new WorldPoint(2147, 2322, 0), false),
		new ShoalWaypoint(new WorldPoint(2153, 2337, 0), false),
	};

	public static final BluefinRainbowReef INSTANCE = new BluefinRainbowReef();
	
	private BluefinRainbowReef() {}

	@Override
	public WorldArea getArea() { return AREA; }
	
	@Override
	public ShoalWaypoint[] getWaypoints() { return WAYPOINTS; }
	
	@Override
	public Shoal getShoalType() { return SHOAL_TYPE; }

}