// ========================================
// Shoal Area Export
// ========================================
// Shoal: Bluefin
// Shoal ID: 59738
// Generated: 2025-12-21 03:06:34
// Total waypoints: 204
// Stop points: 10
// Area-based stop duration: 70 ticks
// ========================================

package com.duckblade.osrs.sailing.features.trawling.ShoalPathData;

import com.duckblade.osrs.sailing.features.trawling.Shoal;
import com.duckblade.osrs.sailing.features.trawling.ShoalWaypoint;
import net.runelite.api.coords.WorldArea;
import net.runelite.api.coords.WorldPoint;

/**
 * Shoal area definition for Bluefin (ID: 59738)
 * Contains waypoint path, area bounds, and stop duration.
 * Generated by ShoalPathTracker on 2025-12-21 03:06:34
 */
public class BluefinRainbowReef {

	/** Area bounds for this shoal region */
	public static final WorldArea AREA = new WorldArea(2099, 2211, 287, 190, 0);

	/** Duration in ticks that shoals stop at each stop point in this area */
	public static final int STOP_DURATION = 70;

	/** Shoal type for this area */
	public static final Shoal SHOAL_TYPE = Shoal.BLUEFIN;

	/** Complete waypoint path with stop point information */
	public static final ShoalWaypoint[] WAYPOINTS = {
		new ShoalWaypoint(new WorldPoint(2153, 2337, 0), true),
		new ShoalWaypoint(new WorldPoint(2154, 2338, 0), false),
		new ShoalWaypoint(new WorldPoint(2155, 2340, 0), false),
		new ShoalWaypoint(new WorldPoint(2157, 2341, 0), false),
		new ShoalWaypoint(new WorldPoint(2159, 2343, 0), false),
		new ShoalWaypoint(new WorldPoint(2161, 2344, 0), false),
		new ShoalWaypoint(new WorldPoint(2162, 2345, 0), false),
		new ShoalWaypoint(new WorldPoint(2164, 2346, 0), false),
		new ShoalWaypoint(new WorldPoint(2185, 2367, 0), false),
		new ShoalWaypoint(new WorldPoint(2187, 2367, 0), false),
		new ShoalWaypoint(new WorldPoint(2189, 2368, 0), false),
		new ShoalWaypoint(new WorldPoint(2191, 2370, 0), false),
		new ShoalWaypoint(new WorldPoint(2194, 2371, 0), false),
		new ShoalWaypoint(new WorldPoint(2196, 2372, 0), false),
		new ShoalWaypoint(new WorldPoint(2198, 2372, 0), false),
		new ShoalWaypoint(new WorldPoint(2200, 2373, 0), false),
		new ShoalWaypoint(new WorldPoint(2201, 2374, 0), false),
		new ShoalWaypoint(new WorldPoint(2203, 2377, 0), false),
		new ShoalWaypoint(new WorldPoint(2203, 2383, 0), false),
		new ShoalWaypoint(new WorldPoint(2202, 2385, 0), false),
		new ShoalWaypoint(new WorldPoint(2197, 2390, 0), false),
		new ShoalWaypoint(new WorldPoint(2195, 2391, 0), false),
		new ShoalWaypoint(new WorldPoint(2164, 2391, 0), false),
		new ShoalWaypoint(new WorldPoint(2158, 2391, 0), false),
		new ShoalWaypoint(new WorldPoint(2155, 2390, 0), false),
		new ShoalWaypoint(new WorldPoint(2153, 2389, 0), false),
		new ShoalWaypoint(new WorldPoint(2150, 2388, 0), false),
		new ShoalWaypoint(new WorldPoint(2149, 2387, 0), false),
		new ShoalWaypoint(new WorldPoint(2148, 2387, 0), false),
		new ShoalWaypoint(new WorldPoint(2147, 2386, 0), false),
		new ShoalWaypoint(new WorldPoint(2147, 2384, 0), true),
		new ShoalWaypoint(new WorldPoint(2147, 2383, 0), false),
		new ShoalWaypoint(new WorldPoint(2146, 2382, 0), false),
		new ShoalWaypoint(new WorldPoint(2145, 2380, 0), false),
		new ShoalWaypoint(new WorldPoint(2144, 2379, 0), false),
		new ShoalWaypoint(new WorldPoint(2142, 2378, 0), false),
		new ShoalWaypoint(new WorldPoint(2142, 2377, 0), false),
		new ShoalWaypoint(new WorldPoint(2141, 2376, 0), false),
		new ShoalWaypoint(new WorldPoint(2135, 2374, 0), false),
		new ShoalWaypoint(new WorldPoint(2133, 2373, 0), false),
		new ShoalWaypoint(new WorldPoint(2132, 2372, 0), false),
		new ShoalWaypoint(new WorldPoint(2130, 2371, 0), false),
		new ShoalWaypoint(new WorldPoint(2127, 2370, 0), false),
		new ShoalWaypoint(new WorldPoint(2119, 2366, 0), false),
		new ShoalWaypoint(new WorldPoint(2116, 2363, 0), false),
		new ShoalWaypoint(new WorldPoint(2115, 2361, 0), false),
		new ShoalWaypoint(new WorldPoint(2113, 2358, 0), false),
		new ShoalWaypoint(new WorldPoint(2113, 2336, 0), false),
		new ShoalWaypoint(new WorldPoint(2115, 2334, 0), false),
		new ShoalWaypoint(new WorldPoint(2116, 2332, 0), false),
		new ShoalWaypoint(new WorldPoint(2119, 2329, 0), false),
		new ShoalWaypoint(new WorldPoint(2121, 2328, 0), false),
		new ShoalWaypoint(new WorldPoint(2124, 2326, 0), false),
		new ShoalWaypoint(new WorldPoint(2127, 2325, 0), false),
		new ShoalWaypoint(new WorldPoint(2129, 2324, 0), false),
		new ShoalWaypoint(new WorldPoint(2130, 2324, 0), false),
		new ShoalWaypoint(new WorldPoint(2131, 2323, 0), false),
		new ShoalWaypoint(new WorldPoint(2133, 2322, 0), false),
		new ShoalWaypoint(new WorldPoint(2136, 2321, 0), true),
		new ShoalWaypoint(new WorldPoint(2137, 2320, 0), false),
		new ShoalWaypoint(new WorldPoint(2139, 2317, 0), false),
		new ShoalWaypoint(new WorldPoint(2139, 2294, 0), false),
		new ShoalWaypoint(new WorldPoint(2138, 2293, 0), false),
		new ShoalWaypoint(new WorldPoint(2138, 2291, 0), false),
		new ShoalWaypoint(new WorldPoint(2137, 2289, 0), false),
		new ShoalWaypoint(new WorldPoint(2137, 2286, 0), false),
		new ShoalWaypoint(new WorldPoint(2136, 2284, 0), false),
		new ShoalWaypoint(new WorldPoint(2136, 2283, 0), false),
		new ShoalWaypoint(new WorldPoint(2133, 2282, 0), false),
		new ShoalWaypoint(new WorldPoint(2128, 2282, 0), false),
		new ShoalWaypoint(new WorldPoint(2125, 2281, 0), false),
		new ShoalWaypoint(new WorldPoint(2124, 2281, 0), false),
		new ShoalWaypoint(new WorldPoint(2113, 2270, 0), false),
		new ShoalWaypoint(new WorldPoint(2112, 2267, 0), false),
		new ShoalWaypoint(new WorldPoint(2110, 2265, 0), false),
		new ShoalWaypoint(new WorldPoint(2109, 2262, 0), false),
		new ShoalWaypoint(new WorldPoint(2109, 2248, 0), true),
		new ShoalWaypoint(new WorldPoint(2109, 2247, 0), false),
		new ShoalWaypoint(new WorldPoint(2110, 2244, 0), false),
		new ShoalWaypoint(new WorldPoint(2112, 2241, 0), false),
		new ShoalWaypoint(new WorldPoint(2112, 2239, 0), false),
		new ShoalWaypoint(new WorldPoint(2113, 2238, 0), false),
		new ShoalWaypoint(new WorldPoint(2114, 2236, 0), false),
		new ShoalWaypoint(new WorldPoint(2115, 2235, 0), false),
		new ShoalWaypoint(new WorldPoint(2119, 2233, 0), false),
		new ShoalWaypoint(new WorldPoint(2134, 2233, 0), false),
		new ShoalWaypoint(new WorldPoint(2135, 2234, 0), false),
		new ShoalWaypoint(new WorldPoint(2137, 2235, 0), false),
		new ShoalWaypoint(new WorldPoint(2140, 2236, 0), false),
		new ShoalWaypoint(new WorldPoint(2144, 2240, 0), false),
		new ShoalWaypoint(new WorldPoint(2145, 2243, 0), false),
		new ShoalWaypoint(new WorldPoint(2147, 2245, 0), false),
		new ShoalWaypoint(new WorldPoint(2148, 2248, 0), false),
		new ShoalWaypoint(new WorldPoint(2148, 2249, 0), false),
		new ShoalWaypoint(new WorldPoint(2149, 2250, 0), false),
		new ShoalWaypoint(new WorldPoint(2150, 2252, 0), false),
		new ShoalWaypoint(new WorldPoint(2151, 2255, 0), false),
		new ShoalWaypoint(new WorldPoint(2155, 2259, 0), false),
		new ShoalWaypoint(new WorldPoint(2157, 2260, 0), false),
		new ShoalWaypoint(new WorldPoint(2159, 2262, 0), false),
		new ShoalWaypoint(new WorldPoint(2173, 2262, 0), false),
		new ShoalWaypoint(new WorldPoint(2181, 2258, 0), false),
		new ShoalWaypoint(new WorldPoint(2183, 2256, 0), false),
		new ShoalWaypoint(new WorldPoint(2185, 2252, 0), false),
		new ShoalWaypoint(new WorldPoint(2185, 2246, 0), true),
		new ShoalWaypoint(new WorldPoint(2185, 2234, 0), false),
		new ShoalWaypoint(new WorldPoint(2186, 2232, 0), false),
		new ShoalWaypoint(new WorldPoint(2187, 2229, 0), false),
		new ShoalWaypoint(new WorldPoint(2188, 2228, 0), false),
		new ShoalWaypoint(new WorldPoint(2189, 2226, 0), false),
		new ShoalWaypoint(new WorldPoint(2193, 2222, 0), false),
		new ShoalWaypoint(new WorldPoint(2195, 2221, 0), false),
		new ShoalWaypoint(new WorldPoint(2227, 2221, 0), false),
		new ShoalWaypoint(new WorldPoint(2246, 2221, 0), false),
		new ShoalWaypoint(new WorldPoint(2248, 2222, 0), false),
		new ShoalWaypoint(new WorldPoint(2249, 2223, 0), false),
		new ShoalWaypoint(new WorldPoint(2251, 2224, 0), false),
		new ShoalWaypoint(new WorldPoint(2252, 2224, 0), false),
		new ShoalWaypoint(new WorldPoint(2255, 2227, 0), false),
		new ShoalWaypoint(new WorldPoint(2256, 2230, 0), false),
		new ShoalWaypoint(new WorldPoint(2256, 2246, 0), false),
		new ShoalWaypoint(new WorldPoint(2257, 2249, 0), false),
		new ShoalWaypoint(new WorldPoint(2258, 2251, 0), false),
		new ShoalWaypoint(new WorldPoint(2261, 2254, 0), false),
		new ShoalWaypoint(new WorldPoint(2264, 2256, 0), false),
		new ShoalWaypoint(new WorldPoint(2266, 2256, 0), false),
		new ShoalWaypoint(new WorldPoint(2267, 2257, 0), false),
		new ShoalWaypoint(new WorldPoint(2271, 2257, 0), true),
		new ShoalWaypoint(new WorldPoint(2297, 2257, 0), false),
		new ShoalWaypoint(new WorldPoint(2299, 2256, 0), false),
		new ShoalWaypoint(new WorldPoint(2306, 2249, 0), false),
		new ShoalWaypoint(new WorldPoint(2308, 2246, 0), false),
		new ShoalWaypoint(new WorldPoint(2308, 2244, 0), false),
		new ShoalWaypoint(new WorldPoint(2309, 2243, 0), false),
		new ShoalWaypoint(new WorldPoint(2310, 2241, 0), false),
		new ShoalWaypoint(new WorldPoint(2311, 2240, 0), false),
		new ShoalWaypoint(new WorldPoint(2314, 2238, 0), false),
		new ShoalWaypoint(new WorldPoint(2317, 2237, 0), false),
		new ShoalWaypoint(new WorldPoint(2320, 2235, 0), false),
		new ShoalWaypoint(new WorldPoint(2347, 2235, 0), false),
		new ShoalWaypoint(new WorldPoint(2351, 2237, 0), false),
		new ShoalWaypoint(new WorldPoint(2354, 2239, 0), false),
		new ShoalWaypoint(new WorldPoint(2356, 2240, 0), false),
		new ShoalWaypoint(new WorldPoint(2358, 2240, 0), false),
		new ShoalWaypoint(new WorldPoint(2359, 2241, 0), false),
		new ShoalWaypoint(new WorldPoint(2363, 2243, 0), false),
		new ShoalWaypoint(new WorldPoint(2374, 2254, 0), false),
		new ShoalWaypoint(new WorldPoint(2375, 2256, 0), false),
		new ShoalWaypoint(new WorldPoint(2375, 2258, 0), false),
		new ShoalWaypoint(new WorldPoint(2376, 2259, 0), false),
		new ShoalWaypoint(new WorldPoint(2376, 2267, 0), true),
		new ShoalWaypoint(new WorldPoint(2376, 2275, 0), false),
		new ShoalWaypoint(new WorldPoint(2375, 2278, 0), false),
		new ShoalWaypoint(new WorldPoint(2372, 2284, 0), false),
		new ShoalWaypoint(new WorldPoint(2362, 2294, 0), false),
		new ShoalWaypoint(new WorldPoint(2358, 2296, 0), false),
		new ShoalWaypoint(new WorldPoint(2355, 2298, 0), false),
		new ShoalWaypoint(new WorldPoint(2352, 2299, 0), false),
		new ShoalWaypoint(new WorldPoint(2349, 2301, 0), false),
		new ShoalWaypoint(new WorldPoint(2343, 2303, 0), false),
		new ShoalWaypoint(new WorldPoint(2338, 2303, 0), true),
		new ShoalWaypoint(new WorldPoint(2318, 2303, 0), false),
		new ShoalWaypoint(new WorldPoint(2316, 2304, 0), false),
		new ShoalWaypoint(new WorldPoint(2314, 2306, 0), false),
		new ShoalWaypoint(new WorldPoint(2313, 2306, 0), false),
		new ShoalWaypoint(new WorldPoint(2311, 2305, 0), false),
		new ShoalWaypoint(new WorldPoint(2306, 2300, 0), false),
		new ShoalWaypoint(new WorldPoint(2304, 2299, 0), false),
		new ShoalWaypoint(new WorldPoint(2303, 2297, 0), false),
		new ShoalWaypoint(new WorldPoint(2302, 2296, 0), false),
		new ShoalWaypoint(new WorldPoint(2300, 2296, 0), false),
		new ShoalWaypoint(new WorldPoint(2299, 2295, 0), false),
		new ShoalWaypoint(new WorldPoint(2298, 2295, 0), false),
		new ShoalWaypoint(new WorldPoint(2296, 2293, 0), false),
		new ShoalWaypoint(new WorldPoint(2290, 2291, 0), false),
		new ShoalWaypoint(new WorldPoint(2288, 2290, 0), false),
		new ShoalWaypoint(new WorldPoint(2283, 2290, 0), false),
		new ShoalWaypoint(new WorldPoint(2282, 2289, 0), false),
		new ShoalWaypoint(new WorldPoint(2280, 2288, 0), false),
		new ShoalWaypoint(new WorldPoint(2269, 2277, 0), false),
		new ShoalWaypoint(new WorldPoint(2265, 2276, 0), false),
		new ShoalWaypoint(new WorldPoint(2264, 2275, 0), false),
		new ShoalWaypoint(new WorldPoint(2258, 2272, 0), true),
		new ShoalWaypoint(new WorldPoint(2238, 2272, 0), false),
		new ShoalWaypoint(new WorldPoint(2235, 2274, 0), false),
		new ShoalWaypoint(new WorldPoint(2233, 2275, 0), false),
		new ShoalWaypoint(new WorldPoint(2201, 2275, 0), false),
		new ShoalWaypoint(new WorldPoint(2199, 2275, 0), true),
		new ShoalWaypoint(new WorldPoint(2168, 2275, 0), false),
		new ShoalWaypoint(new WorldPoint(2162, 2275, 0), false),
		new ShoalWaypoint(new WorldPoint(2160, 2276, 0), false),
		new ShoalWaypoint(new WorldPoint(2159, 2277, 0), false),
		new ShoalWaypoint(new WorldPoint(2155, 2279, 0), false),
		new ShoalWaypoint(new WorldPoint(2152, 2282, 0), false),
		new ShoalWaypoint(new WorldPoint(2150, 2285, 0), false),
		new ShoalWaypoint(new WorldPoint(2149, 2288, 0), false),
		new ShoalWaypoint(new WorldPoint(2147, 2292, 0), false),
		new ShoalWaypoint(new WorldPoint(2147, 2322, 0), false),
		new ShoalWaypoint(new WorldPoint(2147, 2326, 0), false),
		new ShoalWaypoint(new WorldPoint(2148, 2328, 0), false),
		new ShoalWaypoint(new WorldPoint(2150, 2331, 0), false),
		new ShoalWaypoint(new WorldPoint(2151, 2334, 0), false),
		new ShoalWaypoint(new WorldPoint(2152, 2336, 0), false),
		new ShoalWaypoint(new WorldPoint(2153, 2337, 0), false),
	};

	/**
	 * Check if a world point is within this shoal area.
	 */
	public static boolean contains(WorldPoint point) {
		return AREA.contains(point);
	}

	/**
	 * Get all waypoint positions as WorldPoint array (for compatibility).
	 */
	public static WorldPoint[] getPositions() {
		return ShoalWaypoint.getPositions(WAYPOINTS);
	}

	/**
	 * Get stop point indices (for compatibility).
	 */
	public static int[] getStopIndices() {
		return ShoalWaypoint.getStopIndices(WAYPOINTS);
	}

	/**
	 * Get the number of stop points in this area.
	 */
	public static int getStopPointCount() {
		return ShoalWaypoint.getStopPointCount(WAYPOINTS);
	}
}