// ========================================
// Shoal Area Export
// ========================================
// Shoal: Halibut
// Shoal ID: 59737
// Generated: 2025-12-21 16:48:24
// Total waypoints: 229
// Stop points: 8
// Stop duration: Retrieved from Shoal.HALIBUT.getStopDuration()
// ========================================

package com.duckblade.osrs.sailing.features.trawling.ShoalPathData;

import com.duckblade.osrs.sailing.features.trawling.Shoal;
import com.duckblade.osrs.sailing.features.trawling.ShoalAreaData;
import com.duckblade.osrs.sailing.features.trawling.ShoalWaypoint;
import net.runelite.api.coords.WorldArea;
import net.runelite.api.coords.WorldPoint;

/**
 * Shoal area definition for Halibut (ID: 59737)
 * Contains waypoint path and area bounds.
 * Stop duration is retrieved from the Shoal enum.
 * Generated by ShoalPathTracker on 2025-12-21 16:48:24
 */
public class HalibutPortRoberts implements ShoalAreaData {

	/** Area bounds for this shoal region */
	public static final WorldArea AREA = new WorldArea(1821, 3120, 211, 300, 0);

	/** Shoal type for this area */
	public static final Shoal SHOAL_TYPE = Shoal.HALIBUT;

	/** Complete waypoint path with stop point information */
	
	public static final ShoalWaypoint[] WAYPOINTS = {
		new ShoalWaypoint(new WorldPoint(1845, 3290, 0), true),
		new ShoalWaypoint(new WorldPoint(1845, 3313, 0), false),
		new ShoalWaypoint(new WorldPoint(1846, 3314, 0), false),
		new ShoalWaypoint(new WorldPoint(1847, 3317, 0), false),
		new ShoalWaypoint(new WorldPoint(1856, 3326, 0), false),
		new ShoalWaypoint(new WorldPoint(1858, 3327, 0), false),
		new ShoalWaypoint(new WorldPoint(1861, 3329, 0), false),
		new ShoalWaypoint(new WorldPoint(1863, 3330, 0), false),
		new ShoalWaypoint(new WorldPoint(1868, 3330, 0), false),
		new ShoalWaypoint(new WorldPoint(1872, 3332, 0), false),
		new ShoalWaypoint(new WorldPoint(1875, 3333, 0), false),
		new ShoalWaypoint(new WorldPoint(1877, 3334, 0), false),
		new ShoalWaypoint(new WorldPoint(1878, 3335, 0), false),
		new ShoalWaypoint(new WorldPoint(1881, 3335, 0), false),
		new ShoalWaypoint(new WorldPoint(1883, 3336, 0), false),
		new ShoalWaypoint(new WorldPoint(1884, 3337, 0), false),
		new ShoalWaypoint(new WorldPoint(1885, 3339, 0), false),
		new ShoalWaypoint(new WorldPoint(1887, 3342, 0), false),
		new ShoalWaypoint(new WorldPoint(1888, 3344, 0), false),
		new ShoalWaypoint(new WorldPoint(1889, 3347, 0), false),
		new ShoalWaypoint(new WorldPoint(1891, 3351, 0), false),
		new ShoalWaypoint(new WorldPoint(1891, 3353, 0), false),
		new ShoalWaypoint(new WorldPoint(1893, 3357, 0), false),
		new ShoalWaypoint(new WorldPoint(1895, 3360, 0), false),
		new ShoalWaypoint(new WorldPoint(1896, 3363, 0), false),
		new ShoalWaypoint(new WorldPoint(1897, 3365, 0), false),
		new ShoalWaypoint(new WorldPoint(1898, 3368, 0), false),
		new ShoalWaypoint(new WorldPoint(1900, 3370, 0), false),
		new ShoalWaypoint(new WorldPoint(1900, 3372, 0), false),
		new ShoalWaypoint(new WorldPoint(1901, 3373, 0), false),
		new ShoalWaypoint(new WorldPoint(1902, 3375, 0), false),
		new ShoalWaypoint(new WorldPoint(1903, 3376, 0), false),
		new ShoalWaypoint(new WorldPoint(1905, 3377, 0), false),
		new ShoalWaypoint(new WorldPoint(1906, 3377, 0), false),
		new ShoalWaypoint(new WorldPoint(1908, 3376, 0), true),
		new ShoalWaypoint(new WorldPoint(1911, 3376, 0), false),
		new ShoalWaypoint(new WorldPoint(1913, 3377, 0), false),
		new ShoalWaypoint(new WorldPoint(1914, 3378, 0), false),
		new ShoalWaypoint(new WorldPoint(1916, 3381, 0), false),
		new ShoalWaypoint(new WorldPoint(1916, 3383, 0), false),
		new ShoalWaypoint(new WorldPoint(1915, 3386, 0), false),
		new ShoalWaypoint(new WorldPoint(1907, 3394, 0), false),
		new ShoalWaypoint(new WorldPoint(1906, 3396, 0), false),
		new ShoalWaypoint(new WorldPoint(1906, 3399, 0), false),
		new ShoalWaypoint(new WorldPoint(1909, 3402, 0), false),
		new ShoalWaypoint(new WorldPoint(1911, 3403, 0), false),
		new ShoalWaypoint(new WorldPoint(1912, 3404, 0), false),
		new ShoalWaypoint(new WorldPoint(1913, 3406, 0), false),
		new ShoalWaypoint(new WorldPoint(1915, 3408, 0), false),
		new ShoalWaypoint(new WorldPoint(1919, 3410, 0), false),
		new ShoalWaypoint(new WorldPoint(1951, 3410, 0), false),
		new ShoalWaypoint(new WorldPoint(1960, 3410, 0), false),
		new ShoalWaypoint(new WorldPoint(1962, 3409, 0), false),
		new ShoalWaypoint(new WorldPoint(1963, 3408, 0), true),
		new ShoalWaypoint(new WorldPoint(1964, 3406, 0), false),
		new ShoalWaypoint(new WorldPoint(1965, 3403, 0), false),
		new ShoalWaypoint(new WorldPoint(1965, 3378, 0), false),
		new ShoalWaypoint(new WorldPoint(1968, 3372, 0), false),
		new ShoalWaypoint(new WorldPoint(1968, 3371, 0), false),
		new ShoalWaypoint(new WorldPoint(1972, 3367, 0), false),
		new ShoalWaypoint(new WorldPoint(1974, 3366, 0), false),
		new ShoalWaypoint(new WorldPoint(1977, 3365, 0), false),
		new ShoalWaypoint(new WorldPoint(1979, 3363, 0), false),
		new ShoalWaypoint(new WorldPoint(2001, 3363, 0), false),
		new ShoalWaypoint(new WorldPoint(2011, 3358, 0), false),
		new ShoalWaypoint(new WorldPoint(2012, 3357, 0), false),
		new ShoalWaypoint(new WorldPoint(2012, 3356, 0), false),
		new ShoalWaypoint(new WorldPoint(2013, 3354, 0), false),
		new ShoalWaypoint(new WorldPoint(2015, 3352, 0), false),
		new ShoalWaypoint(new WorldPoint(2016, 3349, 0), false),
		new ShoalWaypoint(new WorldPoint(2016, 3326, 0), false),
		new ShoalWaypoint(new WorldPoint(2017, 3324, 0), false),
		new ShoalWaypoint(new WorldPoint(2018, 3321, 0), false),
		new ShoalWaypoint(new WorldPoint(2022, 3313, 0), false),
		new ShoalWaypoint(new WorldPoint(2022, 3296, 0), true),
		new ShoalWaypoint(new WorldPoint(2022, 3293, 0), false),
		new ShoalWaypoint(new WorldPoint(2021, 3291, 0), false),
		new ShoalWaypoint(new WorldPoint(2019, 3289, 0), false),
		new ShoalWaypoint(new WorldPoint(2016, 3287, 0), false),
		new ShoalWaypoint(new WorldPoint(2012, 3285, 0), false),
		new ShoalWaypoint(new WorldPoint(2009, 3284, 0), false),
		new ShoalWaypoint(new WorldPoint(2005, 3282, 0), false),
		new ShoalWaypoint(new WorldPoint(2003, 3282, 0), false),
		new ShoalWaypoint(new WorldPoint(2001, 3281, 0), false),
		new ShoalWaypoint(new WorldPoint(2000, 3280, 0), false),
		new ShoalWaypoint(new WorldPoint(1998, 3277, 0), false),
		new ShoalWaypoint(new WorldPoint(1998, 3272, 0), false),
		new ShoalWaypoint(new WorldPoint(1999, 3270, 0), false),
		new ShoalWaypoint(new WorldPoint(2000, 3267, 0), false),
		new ShoalWaypoint(new WorldPoint(2001, 3265, 0), false),
		new ShoalWaypoint(new WorldPoint(2002, 3262, 0), false),
		new ShoalWaypoint(new WorldPoint(2004, 3260, 0), false),
		new ShoalWaypoint(new WorldPoint(2005, 3257, 0), false),
		new ShoalWaypoint(new WorldPoint(2006, 3255, 0), false),
		new ShoalWaypoint(new WorldPoint(2006, 3237, 0), false),
		new ShoalWaypoint(new WorldPoint(2005, 3236, 0), false),
		new ShoalWaypoint(new WorldPoint(2005, 3235, 0), false),
		new ShoalWaypoint(new WorldPoint(2004, 3234, 0), true),
		new ShoalWaypoint(new WorldPoint(2003, 3234, 0), false),
		new ShoalWaypoint(new WorldPoint(2001, 3233, 0), false),
		new ShoalWaypoint(new WorldPoint(1994, 3233, 0), false),
		new ShoalWaypoint(new WorldPoint(1991, 3234, 0), false),
		new ShoalWaypoint(new WorldPoint(1989, 3235, 0), false),
		new ShoalWaypoint(new WorldPoint(1987, 3237, 0), false),
		new ShoalWaypoint(new WorldPoint(1985, 3238, 0), false),
		new ShoalWaypoint(new WorldPoint(1982, 3239, 0), false),
		new ShoalWaypoint(new WorldPoint(1981, 3240, 0), false),
		new ShoalWaypoint(new WorldPoint(1979, 3240, 0), false),
		new ShoalWaypoint(new WorldPoint(1976, 3239, 0), false),
		new ShoalWaypoint(new WorldPoint(1974, 3238, 0), false),
		new ShoalWaypoint(new WorldPoint(1972, 3236, 0), false),
		new ShoalWaypoint(new WorldPoint(1971, 3234, 0), false),
		new ShoalWaypoint(new WorldPoint(1971, 3232, 0), false),
		new ShoalWaypoint(new WorldPoint(1986, 3206, 0), false),
		new ShoalWaypoint(new WorldPoint(1986, 3176, 0), false),
		new ShoalWaypoint(new WorldPoint(1986, 3165, 0), false),
		new ShoalWaypoint(new WorldPoint(1988, 3160, 0), true),
		new ShoalWaypoint(new WorldPoint(1989, 3158, 0), false),
		new ShoalWaypoint(new WorldPoint(1994, 3140, 0), false),
		new ShoalWaypoint(new WorldPoint(1993, 3138, 0), false),
		new ShoalWaypoint(new WorldPoint(1990, 3135, 0), false),
		new ShoalWaypoint(new WorldPoint(1989, 3133, 0), false),
		new ShoalWaypoint(new WorldPoint(1985, 3131, 0), false),
		new ShoalWaypoint(new WorldPoint(1970, 3140, 0), false),
		new ShoalWaypoint(new WorldPoint(1940, 3140, 0), false),
		new ShoalWaypoint(new WorldPoint(1911, 3140, 0), true),
		new ShoalWaypoint(new WorldPoint(1910, 3140, 0), false),
		new ShoalWaypoint(new WorldPoint(1908, 3141, 0), false),
		new ShoalWaypoint(new WorldPoint(1907, 3142, 0), false),
		new ShoalWaypoint(new WorldPoint(1907, 3145, 0), false),
		new ShoalWaypoint(new WorldPoint(1908, 3148, 0), false),
		new ShoalWaypoint(new WorldPoint(1912, 3152, 0), false),
		new ShoalWaypoint(new WorldPoint(1914, 3153, 0), false),
		new ShoalWaypoint(new WorldPoint(1917, 3155, 0), false),
		new ShoalWaypoint(new WorldPoint(1919, 3156, 0), false),
		new ShoalWaypoint(new WorldPoint(1922, 3157, 0), false),
		new ShoalWaypoint(new WorldPoint(1926, 3159, 0), false),
		new ShoalWaypoint(new WorldPoint(1928, 3159, 0), false),
		new ShoalWaypoint(new WorldPoint(1930, 3160, 0), false),
		new ShoalWaypoint(new WorldPoint(1931, 3161, 0), false),
		new ShoalWaypoint(new WorldPoint(1933, 3164, 0), false),
		new ShoalWaypoint(new WorldPoint(1935, 3189, 0), false),
		new ShoalWaypoint(new WorldPoint(1935, 3210, 0), false),
		new ShoalWaypoint(new WorldPoint(1934, 3212, 0), false),
		new ShoalWaypoint(new WorldPoint(1929, 3217, 0), false),
		new ShoalWaypoint(new WorldPoint(1923, 3220, 0), false),
		new ShoalWaypoint(new WorldPoint(1910, 3220, 0), true),
		new ShoalWaypoint(new WorldPoint(1904, 3217, 0), false),
		new ShoalWaypoint(new WorldPoint(1901, 3215, 0), false),
		new ShoalWaypoint(new WorldPoint(1899, 3214, 0), false),
		new ShoalWaypoint(new WorldPoint(1896, 3213, 0), false),
		new ShoalWaypoint(new WorldPoint(1894, 3212, 0), false),
		new ShoalWaypoint(new WorldPoint(1881, 3199, 0), false),
		new ShoalWaypoint(new WorldPoint(1879, 3198, 0), false),
		new ShoalWaypoint(new WorldPoint(1857, 3198, 0), false),
		new ShoalWaypoint(new WorldPoint(1856, 3200, 0), false),
		new ShoalWaypoint(new WorldPoint(1854, 3201, 0), false),
		new ShoalWaypoint(new WorldPoint(1852, 3203, 0), false),
		new ShoalWaypoint(new WorldPoint(1851, 3205, 0), false),
		new ShoalWaypoint(new WorldPoint(1849, 3206, 0), false),
		new ShoalWaypoint(new WorldPoint(1847, 3208, 0), false),
		new ShoalWaypoint(new WorldPoint(1846, 3210, 0), false),
		new ShoalWaypoint(new WorldPoint(1843, 3213, 0), false),
		new ShoalWaypoint(new WorldPoint(1843, 3214, 0), true),
		new ShoalWaypoint(new WorldPoint(1843, 3214, 0), false),
		new ShoalWaypoint(new WorldPoint(1843, 3233, 0), false),
		new ShoalWaypoint(new WorldPoint(1844, 3235, 0), false),
		new ShoalWaypoint(new WorldPoint(1845, 3236, 0), false),
		new ShoalWaypoint(new WorldPoint(1845, 3237, 0), false),
		new ShoalWaypoint(new WorldPoint(1846, 3238, 0), false),
		new ShoalWaypoint(new WorldPoint(1848, 3239, 0), false),
		new ShoalWaypoint(new WorldPoint(1850, 3241, 0), false),
		new ShoalWaypoint(new WorldPoint(1851, 3243, 0), false),
		new ShoalWaypoint(new WorldPoint(1853, 3244, 0), false),
		new ShoalWaypoint(new WorldPoint(1854, 3245, 0), false),
		new ShoalWaypoint(new WorldPoint(1857, 3246, 0), false),
		new ShoalWaypoint(new WorldPoint(1860, 3248, 0), false),
		new ShoalWaypoint(new WorldPoint(1862, 3249, 0), false),
		new ShoalWaypoint(new WorldPoint(1865, 3250, 0), false),
		new ShoalWaypoint(new WorldPoint(1866, 3251, 0), false),
		new ShoalWaypoint(new WorldPoint(1868, 3251, 0), false),
		new ShoalWaypoint(new WorldPoint(1870, 3252, 0), false),
		new ShoalWaypoint(new WorldPoint(1871, 3253, 0), false),
		new ShoalWaypoint(new WorldPoint(1873, 3256, 0), false),
		new ShoalWaypoint(new WorldPoint(1873, 3258, 0), false),
		new ShoalWaypoint(new WorldPoint(1872, 3261, 0), false),
		new ShoalWaypoint(new WorldPoint(1868, 3263, 0), false),
		new ShoalWaypoint(new WorldPoint(1861, 3263, 0), false),
		new ShoalWaypoint(new WorldPoint(1858, 3261, 0), false),
		new ShoalWaypoint(new WorldPoint(1856, 3260, 0), false),
		new ShoalWaypoint(new WorldPoint(1853, 3259, 0), false),
		new ShoalWaypoint(new WorldPoint(1849, 3257, 0), false),
		new ShoalWaypoint(new WorldPoint(1834, 3257, 0), false),
		new ShoalWaypoint(new WorldPoint(1833, 3259, 0), false),
		new ShoalWaypoint(new WorldPoint(1831, 3261, 0), false),
		new ShoalWaypoint(new WorldPoint(1831, 3264, 0), false),
		new ShoalWaypoint(new WorldPoint(1832, 3266, 0), false),
		new ShoalWaypoint(new WorldPoint(1834, 3269, 0), false),
		new ShoalWaypoint(new WorldPoint(1843, 3278, 0), false),
		new ShoalWaypoint(new WorldPoint(1845, 3282, 0), false),
	};

	// Singleton instance for interface access
	public static final HalibutPortRoberts INSTANCE = new HalibutPortRoberts();
	
	private HalibutPortRoberts() {} // Private constructor
	
	// Interface implementations
	@Override
	public WorldArea getArea() { return AREA; }
	
	@Override
	public ShoalWaypoint[] getWaypoints() { return WAYPOINTS; }
	
	@Override
	public Shoal getShoalType() { return SHOAL_TYPE; }
}

// ========================================
// Integration with ShoalFishingArea enum
// ========================================
// Add this entry to ShoalFishingArea enum:
/*
HALIBUT_AREA(ShoalHalibutArea.INSTANCE),
*/

// ========================================
// Usage Examples
// ========================================
// Check if player is in area:
// boolean inArea = ShoalHalibutArea.INSTANCE.contains(playerLocation);

// Get waypoints for rendering:
// WorldPoint[] path = ShoalHalibutArea.INSTANCE.getPositions();

// Get stop duration (from Shoal enum):
// int duration = ShoalHalibutArea.INSTANCE.getStopDuration();

// Access static fields directly:
// WorldArea area = ShoalHalibutArea.AREA;
// ShoalWaypoint[] waypoints = ShoalHalibutArea.WAYPOINTS;
// Shoal shoalType = ShoalHalibutArea.SHOAL_TYPE;

// ========================================
// Analysis Data
// ========================================
// Area bounds: 1821, 3120, 211, 300
// Stop points: 8 total
// Stop duration: Retrieved from HALIBUT shoal type
// Stop point details:
// Stop 1 (index 0): WorldPoint(x=1845, y=3290, plane=0)
// Stop 2 (index 34): WorldPoint(x=1908, y=3376, plane=0)
// Stop 3 (index 53): WorldPoint(x=1963, y=3408, plane=0)
// Stop 4 (index 74): WorldPoint(x=2022, y=3296, plane=0)
// Stop 5 (index 97): WorldPoint(x=2004, y=3234, plane=0)
// Stop 6 (index 125): WorldPoint(x=1988, y=3160, plane=0)
// Stop 7 (index 146): WorldPoint(x=1911, y=3140, plane=0)
// Stop 8 (index 175): WorldPoint(x=1910, y=3220, plane=0)

// ========================================
// End of Export
// ========================================
