// ========================================
// Shoal Area Export
// ========================================
// Shoal: Halibut
// Shoal ID: 59737
// Generated: 2025-12-21 04:14:57
// Total waypoints: 275
// Stop points: 10
// Area-based stop duration: -1 ticks
// ========================================

package com.duckblade.osrs.sailing.features.trawling.ShoalPathData;

import com.duckblade.osrs.sailing.features.trawling.Shoal;
import com.duckblade.osrs.sailing.features.trawling.ShoalAreaData;
import com.duckblade.osrs.sailing.features.trawling.ShoalWaypoint;
import net.runelite.api.coords.WorldArea;
import net.runelite.api.coords.WorldPoint;

/**
 * Shoal area definition for Halibut (ID: 59737)
 * Contains waypoint path, area bounds, and stop duration.
 * Generated by ShoalPathTracker on 2025-12-21 04:14:57
 */
public class HalibutSouthernExpanse implements ShoalAreaData {

	public static final WorldArea AREA = new WorldArea(1880, 2282, 216, 206, 0);
	public static final Shoal SHOAL_TYPE = Shoal.HALIBUT;

	public static final ShoalWaypoint[] WAYPOINTS = {
		new ShoalWaypoint(new WorldPoint(1922, 2464, 0), true),
		new ShoalWaypoint(new WorldPoint(1910, 2463, 0), false),
		new ShoalWaypoint(new WorldPoint(1906, 2458, 0), false),
		new ShoalWaypoint(new WorldPoint(1912, 2438, 0), true),
		new ShoalWaypoint(new WorldPoint(1914, 2427, 0), false),
		new ShoalWaypoint(new WorldPoint(1927, 2420, 0), false),
		new ShoalWaypoint(new WorldPoint(1939, 2417, 0), false),
		new ShoalWaypoint(new WorldPoint(1938, 2390, 0), false),
		new ShoalWaypoint(new WorldPoint(1913, 2375, 0), false),
		new ShoalWaypoint(new WorldPoint(1905, 2366, 0), false),
		new ShoalWaypoint(new WorldPoint(1905, 2357, 0), true),
		new ShoalWaypoint(new WorldPoint(1904, 2341, 0), false),
		new ShoalWaypoint(new WorldPoint(1900, 2336, 0), false),
		new ShoalWaypoint(new WorldPoint(1890, 2329, 0), false),
		new ShoalWaypoint(new WorldPoint(1891, 2315, 0), false),
		new ShoalWaypoint(new WorldPoint(1908, 2315, 0), false),
		new ShoalWaypoint(new WorldPoint(1920, 2328, 0), false),
		new ShoalWaypoint(new WorldPoint(1932, 2328, 0), true),
		new ShoalWaypoint(new WorldPoint(1952, 2326, 0), false),
		new ShoalWaypoint(new WorldPoint(1966, 2308, 0), false),
		new ShoalWaypoint(new WorldPoint(1995, 2294, 0), false),
		new ShoalWaypoint(new WorldPoint(2001, 2292, 0), true),
		new ShoalWaypoint(new WorldPoint(2030, 2307, 0), false),
		new ShoalWaypoint(new WorldPoint(2046, 2314, 0), false),
		new ShoalWaypoint(new WorldPoint(2058, 2330, 0), false),
		new ShoalWaypoint(new WorldPoint(2054, 2343, 0), false),
		new ShoalWaypoint(new WorldPoint(2054, 2373, 0), false),
		new ShoalWaypoint(new WorldPoint(2050, 2380, 0), false),
		new ShoalWaypoint(new WorldPoint(2037, 2374, 0), true),
		new ShoalWaypoint(new WorldPoint(2025, 2377, 0), false),
		new ShoalWaypoint(new WorldPoint(2021, 2382, 0), false),
		new ShoalWaypoint(new WorldPoint(2023, 2393, 0), false),
		new ShoalWaypoint(new WorldPoint(2051, 2384, 0), false),
		new ShoalWaypoint(new WorldPoint(2060, 2386, 0), false),
		new ShoalWaypoint(new WorldPoint(2061, 2396, 0), false),
		new ShoalWaypoint(new WorldPoint(2057, 2404, 0), false),
		new ShoalWaypoint(new WorldPoint(2076, 2414, 0), false),
		new ShoalWaypoint(new WorldPoint(2086, 2427, 0), false),
		new ShoalWaypoint(new WorldPoint(2080, 2436, 0), false),
		new ShoalWaypoint(new WorldPoint(2063, 2436, 0), true),
		new ShoalWaypoint(new WorldPoint(2032, 2436, 0), false),
		new ShoalWaypoint(new WorldPoint(2011, 2428, 0), false),
		new ShoalWaypoint(new WorldPoint(1998, 2427, 0), false),
		new ShoalWaypoint(new WorldPoint(1990, 2420, 0), false),
		new ShoalWaypoint(new WorldPoint(1987, 2414, 0), true),
		new ShoalWaypoint(new WorldPoint(2012, 2396, 0), false),
		new ShoalWaypoint(new WorldPoint(2021, 2394, 0), false),
		new ShoalWaypoint(new WorldPoint(2022, 2386, 0), false),
		new ShoalWaypoint(new WorldPoint(2009, 2371, 0), false),
		new ShoalWaypoint(new WorldPoint(1979, 2371, 0), false),
		new ShoalWaypoint(new WorldPoint(1962, 2375, 0), false),
		new ShoalWaypoint(new WorldPoint(1960, 2379, 0), false),
		new ShoalWaypoint(new WorldPoint(1960, 2405, 0), true),
		new ShoalWaypoint(new WorldPoint(1962, 2419, 0), false),
		new ShoalWaypoint(new WorldPoint(1976, 2428, 0), false),
		new ShoalWaypoint(new WorldPoint(2005, 2438, 0), false),
		new ShoalWaypoint(new WorldPoint(2011, 2448, 0), false),
		new ShoalWaypoint(new WorldPoint(2002, 2477, 0), false),
		new ShoalWaypoint(new WorldPoint(1987, 2473, 0), false),
		new ShoalWaypoint(new WorldPoint(1984, 2470, 0), true),
		new ShoalWaypoint(new WorldPoint(1979, 2467, 0), false),
		new ShoalWaypoint(new WorldPoint(1968, 2466, 0), false),
		new ShoalWaypoint(new WorldPoint(1960, 2453, 0), false),
		new ShoalWaypoint(new WorldPoint(1955, 2440, 0), false),
		new ShoalWaypoint(new WorldPoint(1950, 2437, 0), false),
		new ShoalWaypoint(new WorldPoint(1934, 2439, 0), false),
		new ShoalWaypoint(new WorldPoint(1931, 2444, 0), false),
		new ShoalWaypoint(new WorldPoint(1929, 2459, 0), false),
		new ShoalWaypoint(new WorldPoint(1922, 2464, 0), false),
	};

	public static final HalibutSouthernExpanse INSTANCE = new HalibutSouthernExpanse();
	
	private HalibutSouthernExpanse() {}

	@Override
	public WorldArea getArea() { return AREA; }
	
	@Override
	public ShoalWaypoint[] getWaypoints() { return WAYPOINTS; }
	
	@Override
	public Shoal getShoalType() { return SHOAL_TYPE; }

}

