// ========================================
// Shoal Area Export
// ========================================
// Shoal: Marlin
// Shoal ID: 59739
// Generated: 2025-12-21 15:45:02
// Total waypoints: 228
// Stop points: 8
// Area-based stop duration: -1 ticks
// ========================================

package com.duckblade.osrs.sailing.features.trawling.ShoalPathData;

import com.duckblade.osrs.sailing.features.trawling.Shoal;
import com.duckblade.osrs.sailing.features.trawling.ShoalAreaData;
import com.duckblade.osrs.sailing.features.trawling.ShoalWaypoint;
import net.runelite.api.coords.WorldArea;
import net.runelite.api.coords.WorldPoint;

/**
 * Shoal area definition for Marlin (ID: 59739)
 * Contains waypoint path, area bounds, and stop duration.
 * Generated by ShoalPathTracker on 2025-12-21 15:45:02
 */
public class MarlinBrittleIsle implements ShoalAreaData {

	public static final WorldArea AREA = new WorldArea(1856, 3963, 222, 158, 0);
	public static final Shoal SHOAL_TYPE = Shoal.MARLIN;

	public static final ShoalWaypoint[] WAYPOINTS = {
		new ShoalWaypoint(new WorldPoint(2026, 4087, 0), true),
		new ShoalWaypoint(new WorldPoint(2044, 4056, 0), false),
		new ShoalWaypoint(new WorldPoint(2058, 4028, 0), false),
		new ShoalWaypoint(new WorldPoint(2068, 4008, 0), false),
		new ShoalWaypoint(new WorldPoint(2068, 3991, 0), true),
		new ShoalWaypoint(new WorldPoint(2055, 3976, 0), false),
		new ShoalWaypoint(new WorldPoint(2049, 3973, 0), false),
		new ShoalWaypoint(new WorldPoint(2018, 3973, 0), false),
		new ShoalWaypoint(new WorldPoint(1986, 3973, 0), false),
		new ShoalWaypoint(new WorldPoint(1965, 3973, 0), false),
		new ShoalWaypoint(new WorldPoint(1937, 3987, 0), false),
		new ShoalWaypoint(new WorldPoint(1909, 4001, 0), false),
		new ShoalWaypoint(new WorldPoint(1895, 4008, 0), false),
		new ShoalWaypoint(new WorldPoint(1884, 4008, 0), true),
		new ShoalWaypoint(new WorldPoint(1878, 4014, 0), false),
		new ShoalWaypoint(new WorldPoint(1890, 4042, 0), false),
		new ShoalWaypoint(new WorldPoint(1906, 4074, 0), false),
		new ShoalWaypoint(new WorldPoint(1921, 4104, 0), false),
		new ShoalWaypoint(new WorldPoint(1924, 4109, 0), true),
		new ShoalWaypoint(new WorldPoint(1927, 4111, 0), false),
		new ShoalWaypoint(new WorldPoint(1951, 4111, 0), false),
		new ShoalWaypoint(new WorldPoint(1967, 4104, 0), false),
		new ShoalWaypoint(new WorldPoint(1982, 4073, 0), false),
		new ShoalWaypoint(new WorldPoint(1998, 4041, 0), false),
		new ShoalWaypoint(new WorldPoint(2012, 4013, 0), false),
		new ShoalWaypoint(new WorldPoint(2016, 4003, 0), false),
		new ShoalWaypoint(new WorldPoint(2016, 3985, 0), true),
		new ShoalWaypoint(new WorldPoint(1995, 3973, 0), false),
		new ShoalWaypoint(new WorldPoint(1980, 3977, 0), false),
		new ShoalWaypoint(new WorldPoint(1953, 3991, 0), false),
		new ShoalWaypoint(new WorldPoint(1925, 4005, 0), false),
		new ShoalWaypoint(new WorldPoint(1911, 4013, 0), false),
		new ShoalWaypoint(new WorldPoint(1902, 4023, 0), false),
		new ShoalWaypoint(new WorldPoint(1905, 4032, 0), false),
		new ShoalWaypoint(new WorldPoint(1919, 4037, 0), false),
		new ShoalWaypoint(new WorldPoint(1932, 4037, 0), true),
		new ShoalWaypoint(new WorldPoint(1963, 4037, 0), false),
		new ShoalWaypoint(new WorldPoint(1988, 4037, 0), false),
		new ShoalWaypoint(new WorldPoint(2016, 4023, 0), false),
		new ShoalWaypoint(new WorldPoint(2026, 4018, 0), false),
		new ShoalWaypoint(new WorldPoint(2031, 4018, 0), true),
		new ShoalWaypoint(new WorldPoint(2049, 4011, 0), false),
		new ShoalWaypoint(new WorldPoint(2051, 4005, 0), false),
		new ShoalWaypoint(new WorldPoint(2023, 3987, 0), false),
		new ShoalWaypoint(new WorldPoint(2016, 3983, 0), false),
		new ShoalWaypoint(new WorldPoint(1985, 3983, 0), false),
		new ShoalWaypoint(new WorldPoint(1953, 3983, 0), false),
		new ShoalWaypoint(new WorldPoint(1928, 3983, 0), true),
		new ShoalWaypoint(new WorldPoint(1917, 3986, 0), false),
		new ShoalWaypoint(new WorldPoint(1901, 4003, 0), false),
		new ShoalWaypoint(new WorldPoint(1887, 4030, 0), false),
		new ShoalWaypoint(new WorldPoint(1873, 4059, 0), false),
		new ShoalWaypoint(new WorldPoint(1866, 4072, 0), false),
		new ShoalWaypoint(new WorldPoint(1866, 4093, 0), false),
		new ShoalWaypoint(new WorldPoint(1875, 4108, 0), false),
		new ShoalWaypoint(new WorldPoint(1909, 4109, 0), false),
		new ShoalWaypoint(new WorldPoint(1941, 4109, 0), false),
		new ShoalWaypoint(new WorldPoint(1973, 4109, 0), false),
		new ShoalWaypoint(new WorldPoint(2003, 4095, 0), false),
		new ShoalWaypoint(new WorldPoint(2021, 4087, 0), false),
	};

	public static final MarlinBrittleIsle INSTANCE = new MarlinBrittleIsle();
	
	private MarlinBrittleIsle() {} // Private constructor
	
	@Override
	public WorldArea getArea() { return AREA; }
	
	@Override
	public ShoalWaypoint[] getWaypoints() { return WAYPOINTS; }
	
	@Override
	public Shoal getShoalType() { return SHOAL_TYPE; }
}

// ========================================
// Integration with ShoalFishingArea enum
// ========================================
// Add this entry to ShoalFishingArea enum:
/*
MARLIN_AREA(ShoalMarlinArea.INSTANCE),
*/

// ========================================
// Usage Examples
// ========================================
// Check if player is in area:
// boolean inArea = ShoalMarlinArea.INSTANCE.contains(playerLocation);

// Get waypoints for rendering:
// WorldPoint[] path = ShoalMarlinArea.INSTANCE.getPositions();

// Get stop duration:
// int duration = ShoalMarlinArea.INSTANCE.getStopDuration();

// Access static fields directly:
// WorldArea area = ShoalMarlinArea.AREA;
// ShoalWaypoint[] waypoints = ShoalMarlinArea.WAYPOINTS;

// ========================================
// Analysis Data
// ========================================
// Area bounds: 1856, 3963, 222, 158
// Stop points: 8 total
// Stop point details:
// Stop 1 (index 0): WorldPoint(x=2026, y=4087, plane=0)
// Stop 2 (index 22): WorldPoint(x=2068, y=3991, plane=0)
// Stop 3 (index 50): WorldPoint(x=1884, y=4008, plane=0)
// Stop 4 (index 76): WorldPoint(x=1924, y=4109, plane=0)
// Stop 5 (index 109): WorldPoint(x=2016, y=3985, plane=0)
// Stop 6 (index 144): WorldPoint(x=1932, y=4037, plane=0)
// Stop 7 (index 158): WorldPoint(x=2031, y=4018, plane=0)
// Stop 8 (index 180): WorldPoint(x=1928, y=3983, plane=0)

// ========================================
// End of Export
// ========================================
